# Basic
alias v='vim'
alias n='nvim'
alias b='bat --style=numbers --color=always --theme=OneHalfDark'
alias t='tmux'
alias ts='date "+%s"'
alias ll='ls -alsG'
alias ls='ls -G'
alias cd..='cd ..'
alias stree='tree -alL 2 -I ".git|.hg|.DS_Store" --filelimit 10'
alias py='python'
alias pyi='python -i'
alias pyt='py -m unittest discover -s __tests__'
alias d='dirs -v'
alias so='source ~/.zshrc'
alias act='source env/bin/activate'
# Facebok stuff
alias cdo='cd ~/fbsource/fbobjc/'
alias cdx='cd ~/fbsource/xplat/'
alias ap='arc pull'
alias as='arc sanity'
alias jfs='jf submit --draft'
alias jfss='jf submit --draft --stack'
alias lint='arc lint -e extra --take DEPS'
# Mercurial
alias hgst='hg status'
alias hgsl='hg sl'
alias hgar='hg addremove'
alias hga='hg amend'
alias hgc='hg commit'
alias hgco='hg checkout'
alias hgcost='hg checkout fbobjc/stable'
alias hgd='hg diff'
alias hgtop='hg next --top'
alias hgbutt='hg prev --bottom'
