export CLICOLORS=1;
export EDITOR=nvim
export VISUAL=nvim

print "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣠⣤⣤⣤⣄⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⣠⡶⠒⠒⠶⣄⣠⡴⠚⠉⠁⠀⠀⠀⠀⠀⠉⠙⠳⢦⡀⠀⠀⠀⠀⠀⠀
⢠⡏⠀⠀⠀⠀⠘⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢧⡀⠀⠀⠀⠀
⢸⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠋⢱⠀⠀⢠⠉⢡⠀⠀⠀⠀⠀⠻⡄⠀⠀⠀
⠀⣧⠀⠀⠀⠀⠀⠀⠀⠀⢸⣧⣾⠄⠀⢸⣦⣾⠀⠀⠀⠀⠀⠀⢻⡄⠀⠀
⠀⠘⢧⡀⠀⠀⠀⠀⠀⠀⠈⣿⣿⠀⠀⠸⣿⡿⠀⠀⠀⠀⠀⠀⠈⠳⣄⠀
⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠈⠁⡴⠶⡆⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠹⡄
⠀⠀⠀⢷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠐⠒⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣷
⠀⠀⠀⠸⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠇
⠀⠀⠀⣀⡿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡽⣿⡛⠁⠀
⠀⣠⢾⣭⠀⠈⠳⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡠⠊⠀⢠⣝⣷⡀
⢠⡏⠘⠋⠀⠀⠀⠈⠑⠦⣄⣀⠀⠀⠀⠀⠀⣀⡠⠔⠋⠀⠀⠀⠈⠛⠃⢻
⠈⠷⣤⣀⣀⣀⣀⣀⣀⣀⣀⣤⡽⠟⠛⠿⣭⣄⣀⣀⣀⣀⣀⣀⣀⣀⣤⠞
⠀⠀⠀⠀⠉⠉⠉⠉⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⠈⠉⠉⠉⠉⠉⠉⠀⠀⠀"
print "######### Welcome! #########\n"

precmd() {
  PROMPT="%F{blue}%B%~%b%f"$'\n'"%B$%b "
}
RPROMPT="%D{%d/%m/%Y %H:%M:%S}" # Display date and time on the right

# pyenv installation
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Directory stack cf. https://thevaluable.dev/zsh-install-configure/
setopt AUTO_PUSHD           # Push the current directory visited on the stack.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.
for index ({1..9}) alias "$index"="cd +${index}"; unset index
# Autocompletion
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots) # With hidden files
# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
# bindkey -v '^?' backward-delete-char
bindkey -e # emacs key bindings
# bindkey -v # vim key bindings

function csv {
    perl -pe 's/((?<=,)|(?<=^)),/ ,/g;' "$1" | column -t -s, | less  -F -S -X -K
}

## FZF
FD_OPTIONS="--hidden --follow --exclude .git --exclude node_modules "
export FZF_DEFAULT_OPTS="--no-mouse --height 50% -1 --reverse --inline-info --pointer · --color dark\
	--preview='[[ \$(file --mime {}) =~ binary ]] && echo {} is a binary file || (bat --style=numbers --color=always --wrap=never --theme=OneHalfDark {} || cat {}) 2> /dev/null | head -300'\
	--preview-window='right:nowrap' \
	--bind='f3:execute(bat --style=numbers --color=always --theme=OneHalfDark {} || less -f {}),ctrl-b:toggle-preview,ctrl-d:half-page-down,ctrl-u:half-page-up,ctrl-a:select-all+accept,ctrl-y:execute-silent(echo {+} | pbcopy),ctrl-x:execute(rm -i {+})+abort'"
export FZF_DEFAULT_COMMAND="fd --type f --type l $FD_OPTIONS"
export FZF_CTRL_T_COMMAND="fd --type f $FD_OPTIONS -E '*.xcodeproj' -E '*.appiconset' -E '*.localized' $FZF_CTRL_T_COMMAND_DIRECTORIES"
export FZF_ALT_C_COMMAND="fd --type d $FD_OPTIONS"
export PATH="/usr/local/opt/e2fsprogs/bin:$PATH"

## Source machine specific code
if [ -f ~/.zsh/zsh-local.zsh ]
then
    source ~/.zsh/zsh-local.zsh
    print "✅ ~/.zsh/zsh-local.zsh found"
else
    print "❌ ~/.zsh/zsh-local.zsh not found"
fi

# Source aliases
if [ -f ~/.zsh/aliases.zsh ]; then
    source ~/.zsh/aliases.zsh
    print "✅ ~/.zsh/aliases.zsh found"
else
    print "❌ ~/.zsh/aliases.zsh not found"
fi

# Autocompletion
if [ -f ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
    source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
    print "✅ ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh found"
else
    print "❌ ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh not found"
fi

# Timer 
if [ -f ~/.zsh/timer.plugin.zsh ]; then
    source ~/.zsh/timer.plugin.zsh
    TIMER_FORMAT='[%d]'; TIMER_PRECISION=2 
    print "✅ ~/.zsh/timer.plugin.zsh found"
else
    print "❌ ~/.zsh/timer.plugin.zsh not found"
fi

# Syntax highlighting 
if [ -f ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
    source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    print "✅ ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
else
    print "❌ ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi

# Fast file
if [ -f ~/.zsh/fastfile.plugin.zsh ]; then
    source ~/.zsh/fastfile.plugin.zsh
    print "✅ ~/.zsh/fastfile.plugin.zsh"
else
    print "❌ ~/.zsh/fastfile.plugin.zsh"
fi

# FZF
if [ -f ~/.zsh/fzf.zsh ]; then
    source ~/.zsh/fzf.zsh
    print "✅ ~/.zsh/fzf.zsh"
else
    print "❌ ~/.zsh/fzf.zsh"
fi
print ""

# Exit code to display, to load after the timer
__exit_code_precmd() {
    result=$(echo $?)
    if [ $result -eq 0 ]; then
        local cols=$((COLUMNS - ${#tdiffstr} - 3))
        echo -e "✅\033[${cols}C ${tdiffstr}"
        #echo -e "\033[42m\033[30m ✅$(printf '%*s' ${cols}) ${tdiffstr}\033[0m"
    else
        local cols=$((COLUMNS - ${#tdiffstr} - 14 - ${#result}))
        echo -e "\033[31m❌ Exit code ${result}\033[0m\033[${cols}C ${tdiffstr}"
        #echo -e "\033[41m ❌ Exit code ${result}$(printf '%*s' ${cols}) ${tdiffstr}\033[0m"
    fi
  #echo -e "%F{black}%(?.%K{green} ✅.%K{red} ❌) ${tdiffstr} %(?.%k. Exit code %? %k)%f"$'\n\n'
  print ""
}

autoload -U add-zsh-hook
add-zsh-hook precmd __exit_code_precmd


# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/julien/.lmstudio/bin"
export PATH="$PATH:$HOME/go/bin"
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/julien/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/julien/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/julien/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/julien/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
